//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TadpatraSplitter.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DIALOG_MANUAL_PROCESSING    108
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_BATCH_PROCESSING     136
#define IDD_DIALOG_TADPATRASPLITTER     138
#define IDD_DIALOG_IMAGE_ANGLE_CORRECTION 139
#define IDB_BITMAP_PREVIOUS_IMAGE       141
#define IDB_BITMAP_NEXT_IMAGE           142
#define IDB_BITMAP_ROTATE_ANTICLOCKWISE 143
#define IDB_BITMAP_ROTATE_CLOCKWISE     144
#define IDC_STATIC_INPUT_FOLDER         1000
#define IDC_EDIT_INPUT_FOLDER           1001
#define IDC_BUTTON_INPUT_FOLDER_BROWSE  1002
#define IDC_BUTTON_START_SPLITTING      1003
#define IDC_STATIC_OUTPUT_FOLDER        1004
#define IDC_EDIT_OUTPUT_FOLDER          1005
#define IDC_BUTTON_OUTPUT_FOLDER_BROWSE 1006
#define IDC_STATIC_IMAGE_TYPE           1007
#define IDC_COMBO_IMAGE_TYPE            1008
#define IDC_STATIC_OUTPUT_BORDER_MARGIN 1009
#define IDC_EDIT_BORDER_PIXEL_MARGIN    1010
#define IDC_SPIN_BORDER_PIXEL_MARGIN    1011
#define IDC_BUTTON_STOP_SPLITTING       1012
#define IDC_SPIN_ROTATE_CLOCKWISE       1012
#define IDC_STATIC_PICTURE_BOX          1014
#define IDC_BUTTON_OPEN_OUTPUT_FOLDER   1015
#define IDC_BUTTON_CLEAN_OUTPUT_FOLDER  1016
#define IDC_STATIC_STATUS               1018
#define IDC_BUTTON_OPEN_INPUT_FOLDER    1019
#define IDC_TAB                         1020
#define IDC_EDIT_FILE_NAME_FRONT_SIDE   1022
#define IDC_EDIT_FILE_NAME_BACK_SIDE    1024
#define IDC_BUTTON_FILE_NAME_FRONT_SIDE 1025
#define IDC_BUTTON_FILE_NAME_BACK_SIDE  1026
#define IDC_STATIC_BACK_SIDE            1029
#define IDC_STATIC_FRONT_SIDE           1030
#define IDC_STATIC_MANUSCRIPT_NUMBER    1031
#define IDC_EDIT_MANUSCRIPT_NUMBER      1032
#define IDC_CHECK_FIRST_FOLIO_IS_TITLE_IMAGE 1033
#define IDC_BUTTON_FOLDER_BROWSE_IMAGE_ROTATION 1034
#define IDC_EDIT_FOLDER                 1035
#define IDC_BUTTON_PREVIOUS_IMAGE       1037
#define IDC_BUTTON_NEXT_IMAGE           1038
#define IDC_STATIC_ROTATE_ANTI_CLOCKWISE 1039
#define IDC_BUTTON_ROTATE_ANTICLOCKWISE 1040
#define IDC_BUTTON_ROTATE_CLOCKWISE     1041
#define IDC_EDIT_ROTATE_ANTI_CLOCKWISE  1042
#define IDC_STATIC_ROTATE_CLOCKWISE     1043
#define IDC_SPIN_ROTATE_ANTICLOCKWISE   1045
#define IDC_EDIT_ROTATE_CLOCKWISE       1046
#define IDC_STATIC_STATUS_CURR_FILE     1047
#define IDC_CHECK_OVERWRITE_ROTATED_FILE 1048
#define IDC_STATIC_ANTI_CLOCKWISE_SHORTCUT 1049
#define IDC_STATIC_CLOCKWISE_SHORTCUT   1050
#define IDC_STATIC_PREVIOUS_IMAGE_SHORTCUT 1051
#define IDC_STATIC_NEXT_IMAGE_SHORTCUT  1052
#define IDC_CHECK1                      1053
#define IDC_CHECK_PREVIEW_IMAGE         1053
#define IDC_EDIT1                       1054
#define IDC_EDIT_STATUS_CURR_FILE       1054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
